# Generated by Django 3.0.7 on 2020-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_page',
            name='rsvp_link',
            field=models.URLField(blank=True),
        ),
    ]
