# Generated by Django 3.0.7 on 2020-06-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
